project:
  title: "Shiny app en quarto"
  type: book
  output-dir: docs

book:
  title: "Shinylive test"
  author: "Erick"
  date: "10/9/2026"
  chapters:
    - index.qmd
    - estatico.qmd
    - shiny-app.qmd
    - shiny-app2.qmd
    - shiny-dashboard-accidentes.qmd

execute:
  cache: false
  freeze: auto

filters:
  - shinylive

format:
  html:
#   theme: 
#     dark: [darkly, darkly-fix.scss]
#     light: [flatly, flatly-fix.scss]
#   highlight-style:
#     dark: nord
#     light: atom-one
#   respect-user-color-scheme: true
#   css: styles.css
  # df-print: paged
    toc: false
  # toc-depth: 5
  # number-sections: true
  # toc-expand: true
    grid:
      sidebar-width: 300px
      body-width: 1300px
      margin-width: 200px
      gutter-width: 1.05rem